### ISSUE TITLE
Incorrect object owning in OpenCL stack between kernel and context

### ISSUE THREAD

**Issue by keryell** [Xilinx/XRT#6239]
It looks like when a `cl_context` is released before a `cl_kernel` depending on that context is released, at `cl_kernel` release time 
an exception is thrown with `No context manager for device` message, which seems to happen in:
```
./runtime_src/core/common/api/context_mgr.cpp:131:  throw std::runtime_error("No context manager for device");
./runtime_src/core/common/api/context_mgr.cpp:142:  throw std::runtime_error("No context manager for device");
```
Problem encountered by @lforg37.
@stsoe I have looked quickly on how dependencies are handled there but I am lost.

**Comment by stsoe** [comment]
@keryell You are down the wrong path.   The code you are looking at has nothing to do with cl_context or cl_kernel or how these object ownerships are managed.

The code is managing contexts on compute units, e.g. managing calls to xclOpenContext and xclCloseContext.    Before a kernel can use a kernel compute unit, it (the compute unit) must be acquired by the calling process.  The context on a compute unit is acquired as part of creating a kernel object.

The exception is an internal error, could be a bug.  But there is not enough background in this issue to determine why the exception is thrown; so please update.

**Comment by lforg37** [comment]
Hello,

Here is the call stack from the debugger:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument

Thread 1 "single_task_vec" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737342416704) at pthread_kill.c:44
44      pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737342416704) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737342416704) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=140737342416704, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007ffff7733476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff77197b7 in __GI_abort () at abort.c:79
#5  0x00007ffff7e48a31 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7e544ec in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7e534b9 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7e53c3a in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7cba484 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#10 0x00007ffff7cbaebe in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#11 0x00007ffff630981a in xrt_core::context_mgr::close_context (device=0x2e7a800, uuid=..., cuidx=...)
    at /storage/lucf/XRT/src/runtime_src/core/common/api/context_mgr.cpp:140
#12 0x00007ffff6377175 in (anonymous namespace)::ip_context::~ip_context (this=0x2e3aff0, __in_chrg=<optimized out>)
    at /storage/lucf/XRT/src/runtime_src/core/common/api/xrt_kernel.cpp:592
#13 0x00007ffff638f9d2 in std::_Sp_counted_ptr<(anonymous namespace)::ip_context*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x2e35c50)
    at /usr/include/c++/11/bits/shared_ptr_base.h:348
#14 0x00007ffff630b022 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x2e35c50) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#15 0x00007ffff630a7e1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x2e35800, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:705
#16 0x00007ffff6376a68 in std::__shared_ptr<(anonymous namespace)::ip_context, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x2e357f8, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#17 0x00007ffff6376a84 in std::shared_ptr<(anonymous namespace)::ip_context>::~shared_ptr (this=0x2e357f8, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr.h:122
#18 0x00007ffff6392866 in xrt::kernel_impl::~kernel_impl (this=0x2e35750, __in_chrg=<optimized out>)
    at /storage/lucf/XRT/src/runtime_src/core/common/api/xrt_kernel.cpp:1438
#19 0x00007ffff63a8fc2 in __gnu_cxx::new_allocator<xrt::kernel_impl>::destroy<xrt::kernel_impl> (this=0x2e35750, __p=0x2e35750)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/11/ext/new_allocator.h:168
#20 0x00007ffff63a8e61 in std::allocator_traits<std::allocator<xrt::kernel_impl> >::destroy<xrt::kernel_impl> (__a=..., __p=0x2e35750)
    at /usr/include/c++/11/bits/alloc_traits.h:531
#21 0x00007ffff63a8b57 in std::_Sp_counted_ptr_inplace<xrt::kernel_impl, std::allocator<xrt::kernel_impl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x2e35740)
    at /usr/include/c++/11/bits/shared_ptr_base.h:528
#22 0x00007ffff67fc048 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x2e35740) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#23 0x00007ffff67fba31 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x2e2fac0, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:705
#24 0x00007ffff68e78a6 in std::__shared_ptr<xrt::kernel_impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x2e2fab8, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#25 0x00007ffff68e78c6 in std::shared_ptr<xrt::kernel_impl>::~shared_ptr (this=0x2e2fab8, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr.h:122
#26 0x00007ffff68e78e6 in xrt::kernel::~kernel (this=0x2e2fab8, __in_chrg=<optimized out>) at /storage/lucf/XRT/src/runtime_src/core/include/xrt/xrt_kernel.h:563
#27 0x00007ffff68e8dfe in xocl::kernel::xkr::~xkr (this=0x2e2fab8, __in_chrg=<optimized out>) at /storage/lucf/XRT/src/runtime_src/xocl/core/kernel.h:388
#28 0x00007ffff68f2cfc in std::pair<xocl::device const* const, xocl::kernel::xkr>::~pair (this=0x2e2fab0, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/stl_pair.h:211
#29 0x00007ffff68f2d20 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<xocl::device const* const, xocl::kernel::xkr> > >::destroy<std::pair<xocl::device const* const, xocl::kernel::xkr> > (this=0x2e9b938, __p=0x2e2fab0) at /usr/include/c++/11/ext/new_allocator.h:168
#30 0x00007ffff68f17b3 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<xocl::device const* const, xocl::kernel::xkr> > > >::destroy<std::pair<xocl::device const* const, xocl::kernel::xkr> > (__a=..., __p=0x2e2fab0) at /usr/include/c++/11/bits/alloc_traits.h:531
#31 0x00007ffff68ef869 in std::_Rb_tree<xocl::device const*, std::pair<xocl::device const* const, xocl::kernel::xkr>, std::_Select1st<std::pair<xocl::device const* const, xocl::kernel::xkr> >, std::less<xocl::device const*>, std::allocator<std::pair<xocl::device const* const, xocl::kernel::xkr> > >::_M_destroy_node (this=0x2e9b938, 
    __p=0x2e2fa90) at /usr/include/c++/11/bits/stl_tree.h:623
#32 0x00007ffff68ed6d1 in std::_Rb_tree<xocl::device const*, std::pair<xocl::device const* const, xocl::kernel::xkr>, std::_Select1st<std::pair<xocl::device const* const, xocl::kernel::xkr> >, std::less<xocl::device const*>, std::allocator<std::pair<xocl::device const* const, xocl::kernel::xkr> > >::_M_drop_node (this=0x2e9b938, 
    __p=0x2e2fa90) at /usr/include/c++/11/bits/stl_tree.h:631
#33 0x00007ffff68eae47 in std::_Rb_tree<xocl::device const*, std::pair<xocl::device const* const, xocl::kernel::xkr>, std::_Select1st<std::pair<xocl::device const* const, xocl::kernel::xkr> >, std::less<xocl::device const*>, std::allocator<std::pair<xocl::device const* const, xocl::kernel::xkr> > >::_M_erase (this=0x2e9b938, 
--Type <RET> for more, q to quit, c to continue without paging--
    __x=0x2e2fa90) at /usr/include/c++/11/bits/stl_tree.h:1889
#34 0x00007ffff68e93aa in std::_Rb_tree<xocl::device const*, std::pair<xocl::device const* const, xocl::kernel::xkr>, std::_Select1st<std::pair<xocl::device const* const, xocl::kernel::xkr> >, std::less<xocl::device const*>, std::allocator<std::pair<xocl::device const* const, xocl::kernel::xkr> > >::~_Rb_tree (this=0x2e9b938, 
    __in_chrg=<optimized out>) at /usr/include/c++/11/bits/stl_tree.h:984
#35 0x00007ffff68e8d6e in std::map<xocl::device const*, xocl::kernel::xkr, std::less<xocl::device const*>, std::allocator<std::pair<xocl::device const* const, xocl::kernel::xkr> > >::~map (this=0x2e9b938, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/stl_map.h:302
#36 0x00007ffff68e5d52 in xocl::kernel::~kernel (this=0x2e9b870, __in_chrg=<optimized out>) at /storage/lucf/XRT/src/runtime_src/xocl/core/kernel.cpp:248
#37 0x00007ffff68e5de6 in xocl::kernel::~kernel (this=0x2e9b870, __in_chrg=<optimized out>) at /storage/lucf/XRT/src/runtime_src/xocl/core/kernel.cpp:248
#38 0x00007ffff6840323 in xocl::clReleaseKernel (kernel=0x2e9b880) at /storage/lucf/XRT/src/runtime_src/xocl/api/clReleaseKernel.cpp:41
```
The program fails at each run, but the error is not always the same:

+ Under debugging it seems to be consistently this `std::system_error`,
+ without the debugger, the error is mostly the `std::runtime_error` shown above,
+ but sometimes the termination is even due to a segfault.

Each time, according to the trace, the issue comes in the call of clKernelRelease.

Here is the call trace generated by XRT:

```
STRUCTURE
Group_Start,Native API Host Trace
Dynamic_Row,1,Native XRT API Calls,API Events
Group_Start,Host to Device Data Transfers
Dynamic_Row,2,Reads,Read Transfers
Dynamic_Row,3,Writes,Write Transfers
Group_End,Host to Device Data Transfers
Group_End,Native API Host Trace

MAPPING
35,0:0:0
33,1:1:1
36,READ
29,WRITE
27,bank0
15,clBuildProgram
11,clCreateBuffer
10,clCreateCommandQueue
8,clCreateContext
16,clCreateKernel
13,clCreateProgramWithBinary
25,clEnqueueMapBuffer
23,clEnqueueNDRangeKernel
38,clEnqueueUnmapMemObject
12,clGetContextInfo
4,clGetDeviceIDs
5,clGetDeviceInfo
1,clGetExtensionFunctionAddress
2,clGetExtensionFunctionAddressForPlatform
19,clGetKernelInfo
3,clGetPlatformInfo
40,clReleaseCommandQueue
7,clReleaseDevice
39,clReleaseEvent
37,clReleaseMemObject
6,clRetainDevice
20,clSetKernelArg
26,clWaitForEvents
32,handlerEE_clES2_E3add_eCM5g51B
31,single_task_vector_add-186c03
30,xilinx_u200_gen3x16_xdma_base_1
24,xrt::bo::address
21,xrt::bo::bo
22,xrt::bo::map
28,xrt::bo::sync
9,xrt::device::device
14,xrt::device::load_xclbin
17,xrt::kernel::kernel
18,xrt::run::run
34,xrt::run::start

EVENTS
60,0,8.091689,1,API_CALL,9
61,60,211.335795,1,API_CALL,9
112,0,565.987036,1,API_CALL,14
113,112,635.291363,1,API_CALL,14
134,0,755.546761,1,API_CALL,17
135,134,755.961004,1,API_CALL,17
136,0,756.023340,1,API_CALL,18
137,136,756.097766,1,API_CALL,18
166,0,758.329111,1,API_CALL,21
167,166,758.388925,1,API_CALL,21
168,0,758.786464,1,API_CALL,22
169,168,758.787620,1,API_CALL,22
178,0,759.617852,1,API_CALL,21
179,178,759.672278,1,API_CALL,21
188,0,760.425785,1,API_CALL,21
189,188,760.491448,1,API_CALL,21
190,0,760.558396,1,API_CALL,22
191,190,760.559213,1,API_CALL,22
200,0,762.070911,1,API_CALL,24
201,200,762.071793,1,API_CALL,24
202,0,762.104559,1,API_CALL,24
203,202,762.104969,1,API_CALL,24
204,0,762.149452,1,API_CALL,24
205,204,762.149854,1,API_CALL,24
210,0,762.843679,1,API_CALL,22
211,210,762.844415,1,API_CALL,22
214,0,763.223039,1,API_CALL,24
215,214,763.224006,1,API_CALL,24
216,0,763.247736,1,API_CALL,24
217,216,763.248236,1,API_CALL,24
219,0,763.296625,1,API_CALL,24
220,219,763.297229,1,API_CALL,24
221,0,763.334090,1,API_CALL,24
222,221,763.334730,1,API_CALL,24
223,0,763.376046,1,API_CALL,22
224,223,763.376738,1,API_CALL,22
225,0,763.413383,1,API_CALL,28
225,0,763.413383,3,API_CALL,29
226,225,763.445025,1,API_CALL,28
226,225,763.445025,3,API_CALL,29
227,0,763.525382,1,API_CALL,28
227,0,763.525382,3,API_CALL,29
228,227,763.571392,1,API_CALL,28
228,227,763.571392,3,API_CALL,29
229,0,763.632887,1,API_CALL,22
230,229,763.633646,1,API_CALL,22
231,0,763.658388,1,API_CALL,28
231,0,763.658388,3,API_CALL,29
232,231,763.684911,1,API_CALL,28
232,231,763.684911,3,API_CALL,29
234,0,763.760179,1,API_CALL,24
235,234,763.760825,1,API_CALL,24
236,0,763.776104,1,API_CALL,24
237,236,763.776483,1,API_CALL,24
239,0,763.938280,1,API_CALL,34
240,239,763.969209,1,API_CALL,34
242,0,770.933838,1,API_CALL,24
243,242,770.935894,1,API_CALL,24
244,0,770.957144,1,API_CALL,24
245,244,770.957463,1,API_CALL,24
247,0,770.991239,1,API_CALL,24
248,247,770.991619,1,API_CALL,24
249,0,771.004382,1,API_CALL,24
250,249,771.004685,1,API_CALL,24
251,0,771.060950,1,API_CALL,28
251,0,771.060950,2,API_CALL,36
252,251,771.106408,1,API_CALL,28
252,251,771.106408,2,API_CALL,36
253,0,771.178202,1,API_CALL,22
254,253,771.179235,1,API_CALL,22
256,0,771.231150,1,API_CALL,24
257,256,771.231848,1,API_CALL,24
258,0,771.251344,1,API_CALL,24
259,258,771.251816,1,API_CALL,24
277,0,772.629281,1,API_CALL,24
278,277,772.630095,1,API_CALL,24
279,0,772.645219,1,API_CALL,24
280,279,772.645579,1,API_CALL,24
282,0,772.679187,1,API_CALL,24
283,282,772.679666,1,API_CALL,24
284,0,772.693245,1,API_CALL,24
285,284,772.693569,1,API_CALL,24
287,0,772.740705,1,API_CALL,24
288,287,772.741417,1,API_CALL,24
289,0,772.752513,1,API_CALL,24
290,289,772.752787,1,API_CALL,24
```

**Comment by stsoe** [comment]
@lforg37 Can we get a CR please, with a STR (steps-to-reproduce)?  Thanks!

**Comment by lforg37** [comment]
That is CR-1121712. It seems that the bug disappear when no custom xrt.ini is provided, so for the record, here is the problematic xrt.ini:

```
[Runtime]
runtime_log = xrtoutlog
hal_log = hal.log
runtime.verbosity = 5

[Emulation]
print_infos_in_console = true
print_warnings_in_console = true
print_errors_in_console = true

[Debug]
native_xrt_trace = true
app_debug = true
data_trace = coarse
opencl_trace = true
continuous_trace = true
```

**Comment by stsoe** [comment]
A CR has been filed against profiling.  XRT's object ownership appears correct.
