### ISSUE TITLE
what():  failed to close cu context (0): Invalid argument

### ISSUE THREAD

**Issue by moore-ch** [Xilinx/XRT#7563]
Hi, XRT team,

in edge, I encountered one issue when xrt::kernel deconstruction, please help on this, thanks!

1. my usage:
    my class has members in sequence: 
            std::vector<std::unique_ptr<xrt::device>> devices_;
            std::map<std::string, DeviceObject> cu_handles_;
    and struct DeviceObject has member:
            std::unique_ptr<xrt::kernel> kernel;
            std::unique_ptr<xrt::ip> ip;
    the initialization in sequence:
            devices_.emplace_back(std::make_unique<xrt::device>(deviceIndex));
            ............some other codes..................
            cu.kernel = std::make_unique<xrt::kernel>(*device, device_uuid, cu_name);
            cu.kernel = std::make_unique<xrt::kernel>(*device, device_uuid, cu_name);
2. all the device operations are correct like load xclbin and get some registers.
3. but when ~DeviceObject(), there occurs an exception:
           terminate called after throwing an instance of 'xrt_core::system_error'
           what():  failed to close cu context (0): Invalid argument
4. the stack is as below:
           #0  0x0000fffff7ba4c58 in ?? () from /lib/libc.so.6
           #1  0x0000fffff7b60c10 in raise () from /lib/libc.so.6
           #2  0x0000fffff7b4dd64 in abort () from /lib/libc.so.6
           #3  0x0000fffff7d93774 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/libstdc++.so.6
           #4  0x0000fffff7d91110 in ?? () from /usr/lib/libstdc++.so.6
           #5  0x0000fffff7d8ff48 in ?? () from /usr/lib/libstdc++.so.6
           #6  0x0000fffff7d907c8 in __gxx_personality_v0 () from /usr/lib/libstdc++.so.6
           #7  0x0000fffff7cd814c in ?? () from /lib/libgcc_s.so.1
           #8  0x0000fffff7cd8714 in _Unwind_Resume () from /lib/libgcc_s.so.1
           #9  0x0000fffff79060c4 in xrt_core::context_mgr::close_context(xrt::hw_context const&, xrt_core::cuidx_type) () from /usr/lib/libxrt_coreutil.so.2
           #10 0x0000fffff792b724 in ?? () from /usr/lib/libxrt_coreutil.so.2
           #11 0x0000fffff7937bcc in ?? () from /usr/lib/libxrt_coreutil.so.2
           #12 0x0000aaaaaaaa2f94 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0xaaaaaad10b00)
    at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/c++/11.2.0/bits/shared_ptr_base.h:168
           #13 0x0000aaaaaaaa2d10 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0xaaaaaabe0f08, __in_chrg=<optimized out>)
    at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/c++/11.2.0/bits/shared_ptr_base.h:705
           #14 0x0000fffff7f997b0 in std::__shared_ptr<xrt::kernel_impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0xaaaaaabe0f00, __in_chrg=<optimized out>)
    at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/c++/11.2.0/bits/shared_ptr_base.h:1154
           #15 0x0000fffff7f997d8 in std::shared_ptr<xrt::kernel_impl>::~shared_ptr (this=0xaaaaaabe0f00, __in_chrg=<optimized out>)
    at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/c++/11.2.0/bits/shared_ptr.h:122
           #16 0x0000fffff7f99800 in xrt::kernel::~kernel (this=0xaaaaaabe0f00, __in_chrg=<optimized out>) at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/xrt/xrt/xrt_kernel.h:549
           #17 0x0000fffff7f9e4d4 in std::default_delete<xrt::kernel>::operator() (this=0xaaaaaad10a50, __ptr=0xaaaaaabe0f00)
    at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/c++/11.2.0/bits/unique_ptr.h:85
           #18 0x0000fffff7f9c30c in std::unique_ptr<xrt::kernel, std::default_delete<xrt::kernel> >::~unique_ptr (this=0xaaaaaad10a50, __in_chrg=<optimized out>)
    at /opt/petalinux/2022.2/sysroots/cortexa72-cortexa53-xilinx-linux/usr/include/c++/11.2.0/bits/unique_ptr.h:361
           #19 0x0000fffff7f97d8c in (anonymous namespace)::DeviceObject::~DeviceObject (this=0xaaaaaad107e0, __in_chrg=<optimized out>) at /workspace/vart/xrt-device-handle/src/./xrt_device_handle_imp.hpp:58

**Comment by stsoe** [comment]
@moore-ch I don't understand the code?  Need more context, please.  
If the cu close fails it is because the device has already be closed.
Please paste the stack in pre-formatted mode to prevent interpretation of `#`.
